// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    CommentInput: typeof import('./src/components/CommentInput.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    FormEdit: typeof import('./src/components/FormEdit.vue')['default']
    IonArrowUp: typeof import('./src/components/IonArrowUp.vue')['default']
    IonBack: typeof import('./src/components/IonBack.vue')['default']
    IonChat: typeof import('./src/components/IonChat.vue')['default']
    IonEdit: typeof import('./src/components/IonEdit.vue')['default']
    IonPerson: typeof import('./src/components/IonPerson.vue')['default']
    IonReply: typeof import('./src/components/IonReply.vue')['default']
    IonTrash: typeof import('./src/components/IonTrash.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
  }
}
